// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aula06.Domain.Entities;

public partial class Pedido
{
    public int Id { get; set; }

    public DateTime DataPedido { get; set; }

    public double? ValorPedido { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdProduto { get; set; }

    public int? IdCliente { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}