// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aula06.Domain.Entities;

public partial class Produto
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public int Quantidade { get; set; }

    public double? Preco { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}